### ISSUE TITLE
ContainerMetric

### ISSUE THREAD

**Issue by bobbyhubbard** [rakutentech/kafka-firehose-nozzle#15]
I havent actually pushed this to test but curious if this statement in your readme is still true...

`Currently we only support LogMessage and ValueMetric events (We will support others soon).`

I found `ContainerMetric` events in the code but just want to verify.

THanks!

**Comment by CAFxX** [comment]
@bobbyhubbard we're working on adding the missing message types in #16

**Comment by bobbyhubbard** [comment]
Fantastic. Appreciate the update.

**Comment by CAFxX** [comment]
Fixed in #16
