### ISSUE TITLE
Possible binary build?

### ISSUE THREAD

**Issue by bradgoodman** [rakutentech/kafka-firehose-nozzle#23]
Is it possible to have this project built as a binary? Our organization doesn't have access to public Github or the internet so it is nearly impossible to build a project in Go. If we had a binary I could deploy via the binary buildpack in PCF and set all the variables in the environment of the application.

**Comment by CAFxX** [comment]
@bradgoodman all dependencies should be vendored, so internet connectivity during staging/building or runtime is not required. Are you experiencing problems deploying to a PCF with no internet connectivity? Can you post the relevant logs?

**Comment by bradgoodman** [comment]
Would we need to set the environment variables in the application or in the .toml file?

**Comment by CAFxX** [comment]
Most configurations should be put in the toml file. We only support env vars for some credentials (e.g. to access UAA)
